# This is a basic workflow to help you get started with Actions

name: docker-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push container 1
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.app1 
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:app1-${{ github.ref_name }}-${{ env.SHORT_SHA }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max
          provenance: false 

      - name: Build and push container 2
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.app2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:app2-${{ github.ref_name }}-${{ env.SHORT_SHA }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max
          provenance: false

